fix: Lint

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -21,9 +21,9 @@ download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 #  Extract contents of tar.gz file into the download directory
 if [ "$ext" == "tar.gz" ]; then
-  tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+	tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 else
-  unzip -qq "${release_file}" -d "${ASDF_DOWNLOAD_PATH}" || fail "Could not extract $release_file"
+	unzip -qq "${release_file}" -d "${ASDF_DOWNLOAD_PATH}" || fail "Could not extract $release_file"
 fi
 
 # Remove the tar.gz file since we don't need to keep it
